spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_NAME:live-coding}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:root}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: false
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/liquibase/main.xml
    enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
